set_property SRC_FILE_INFO {cfile:C:/Users/Asus/my_first_project/my_first_project.srcs/constrs_1/new/constrainsts.xdc rfile:../../../my_first_project.srcs/constrs_1/new/constrainsts.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M16 [get_ports c]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U1 [get_ports a]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V1 [get_ports b]
